spring.application.name=instantmodels
server.port=${PORT:8080}
logging.level.root=WARN
logging.level.com.example.instantmodels=INFO
logging.level.com.azure.identity=ERROR
logging.level.com.microsoft.aad.msal4j=ERROR