org.slf4j.simpleLogger.defaultLogLevel=warn
org.slf4j.simpleLogger.log.com.azure.identity=error
org.slf4j.simpleLogger.log.com.microsoft.aad.msal4j=error
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false